image:
  repository: bartoszduch/locust
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8089

locust:
  host: http://192.168.49.2:32405
  users: 50
  spawnRate: 10
  runTime: 5m
